[package]
name = "obbidl-cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
obbidl-lib = { path = "../obbidl-lib" }
askama = "0.12.0"
open = "5.0.0"
