[package]
name = "obbidl-lib"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.11.0"
strum = { version = "0.25.0", features = ["derive"] }
colored = "2.0.4"
display_utils = "0.4.0"
