[package]
name = "obbidl-derive"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
obbidl = { path = "../obbidl-rs" }
quote = "1.0.33"
syn = "2.0.28"

[lib]
proc-macro = true
